# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal
dist: bionic

# no install step to perform
install: true

# When a script command fails, travis run the next one so we must use
# `travis_terminate 1`
script:
  - >
    echo 'travis_fold:start:env'
    && make --directory=ci env
    && echo 'travis_fold:end:env'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:devel'
    && make --directory=ci devel
    && echo 'travis_fold:end:devel'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:build'
    && make --directory=ci build
    && echo 'travis_fold:end:build'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:test'
    && make --directory=ci test
    && echo 'travis_fold:end:test'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:install_env'
    && make --directory=ci install_env
    && echo 'travis_fold:end:install_env'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:install_devel'
    && make --directory=ci install_devel
    && echo 'travis_fold:end:install_devel'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:install_build'
    && make --directory=ci install_build
    && echo 'travis_fold:end:install_build'
    || travis_terminate 1

  - >
    echo 'travis_fold:start:install_test'
    && make --directory=ci install_test
    && echo 'travis_fold:end:install_test'
    || travis_terminate 1
