function(BUILD_DOC TARGET)
	find_package(Doxygen)
	if(DOXYGEN_FOUND)
		if(NOT DEFINED CMAKE_DOCUMENTATION_OUTPUT_DIRECTORY)
			set(CMAKE_DOCUMENTATION_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/doc)
		endif()

		configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile @ONLY)
		file(GLOB_RECURSE _SRCS "../doc/*" "../include/*" "../src/*")
		add_custom_target(${TARGET}_doc ALL
			#COMMAND ${CMAKE_COMMAND} -E echo "Target ${TARGET}_doc"
			SOURCES Doxyfile.in ${_SRCS}
			DEPENDS ${ARGN} ${CMAKE_DOCUMENTATION_OUTPUT_DIRECTORY}/${TARGET}
			WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
			COMMENT "Generating ${TARGET} doxygen documentation" VERBATIM
			)
		add_custom_command(OUTPUT ${CMAKE_DOCUMENTATION_OUTPUT_DIRECTORY}/${TARGET}
			#COMMAND ${CMAKE_COMMAND} -E echo "Command ${TARGET}_doc"
			COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_DOCUMENTATION_OUTPUT_DIRECTORY}/${TARGET}"
			COMMAND ${DOXYGEN_EXECUTABLE} Doxyfile 1 > /dev/null
			DEPENDS Doxyfile.in ${_SRCS} ${ARGN}
			WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
			)
		install(DIRECTORY ${CMAKE_DOCUMENTATION_OUTPUT_DIRECTORY}/${TARGET} DESTINATION share/doc)
	endif()
endfunction()
