name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env
    - name: Build project
      run: make --directory=ci devel
    - name: Test project
      run: make --directory=ci test_devel
